# Generated by Django 3.0.3 on 2020-03-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('account_id', models.IntegerField(db_column='ACCOUNT_ID', primary_key=True, serialize=False)),
                ('account_name', models.CharField(db_column='ACCOUNT_NAME', max_length=45)),
                ('time_updated', models.DateTimeField(db_column='TIME_UPDATED')),
            ],
            options={
                'db_table': 'account_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('project_id', models.IntegerField(db_column='PROJECT_ID', primary_key=True, serialize=False)),
                ('project_name', models.CharField(db_column='PROJECT_NAME', max_length=45)),
                ('start_date', models.DateField(db_column='START_DATE')),
                ('end_date', models.DateField(db_column='END_DATE')),
                ('time_updated', models.DateTimeField(db_column='TIME_UPDATED')),
            ],
            options={
                'db_table': 'project_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceDetail',
            fields=[
                ('resource_id', models.IntegerField(db_column='RESOURCE_ID', primary_key=True, serialize=False)),
                ('resource_name', models.CharField(db_column='RESOURCE_NAME', max_length=45)),
                ('technology', models.CharField(db_column='TECHNOLOGY', max_length=40)),
                ('doj', models.DateField(db_column='DOJ')),
                ('time_updated', models.DateTimeField(db_column='TIME_UPDATED')),
            ],
            options={
                'db_table': 'resource_detail',
                'managed': False,
            },
        ),
    ]
