# Generated by Django 3.0.3 on 2020-03-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('account_id', models.IntegerField(db_column='ACCOUNT_ID', primary_key=True, serialize=False)),
                ('account_name', models.CharField(db_column='ACCOUNT_NAME', max_length=100)),
                ('time_updated', models.DateTimeField(db_column='TIME_UPDATED')),
            ],
            options={
                'db_table': 'account_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('project_id', models.IntegerField(db_column='PROJECT_ID', primary_key=True, serialize=False)),
                ('project_name', models.CharField(db_column='PROJECT_NAME', max_length=45)),
                ('start_date', models.DateTimeField(db_column='START_DATE')),
                ('end_date', models.DateTimeField(db_column='END_DATE')),
                ('time_updated', models.CharField(db_column='TIME_UPDATED', max_length=45)),
            ],
            options={
                'db_table': 'project_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceDetails',
            fields=[
                ('resource_id', models.IntegerField(db_column='RESOURCE_ID', primary_key=True, serialize=False)),
                ('resource_name', models.CharField(db_column='RESOURCE_NAME', max_length=45)),
                ('technology', models.CharField(db_column='TECHNOLOGY', max_length=24)),
                ('doj', models.DateField(db_column='DOJ')),
                ('time_updated', models.DateTimeField(db_column='TIME_UPDATED')),
            ],
            options={
                'db_table': 'resource_details',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AccountDetail',
        ),
        migrations.DeleteModel(
            name='ProjectDetail',
        ),
        migrations.DeleteModel(
            name='ResourceDetail',
        ),
    ]
