# Generated by Django 3.0.3 on 2020-03-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200306_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountdetails',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectdetails',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resourcedetails',
            options={},
        ),
    ]
